FROM almalinux:8
RUN yum install nginx -y
EXPOSE 80/tcp
CMD ["nginx","-g","daemon off"]


#Expose is used to just for information purpose. We can show the posrt number to user.
#docker build -t expose:v1 .
#docker images
#docker inspect <IMAGE ID> 




