FROM almalinux:8
LABEL Trainer="kondareddy" \
      Course="Devops" \
      Duration="120HRS"



   #LABEL help to filter the images..
  #docker build -t label:v1 .
  #docker images
  #docker images --filter label=Trainer      
      