FROM almalinux:8
RUN yum install nginx -y
CMD ["nginx","-g","daemon off;"]


#docker build -t nginx:v2 .
#dokcer run -p 8080:80 nginx:v2
#docker run -d -p 8090:80 --name nginx nginx:v2
#docker ps
#docker ps -a
#docker ps -a -q
#dokcer rm <id>
#dokcer rm `docker ps -a -q`
