FROM almalinux:8
RUN adduser kondareddy
USER kondareddy
CMD ["sleep", "100"]

#USER give the permition.
# docker build -t user:v1
# docker run -d user:v1
# docker exec -it 6154bb640 bash
# ps -ef | grep user
